// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: security-intro
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2018-08-11
:page-description: Learn how to secure a web application through authentication and authorization.
:page-tags: ['REST', 'MicroProfile', 'Security', 'CDI']
:page-related-guides: ['microprofile-jwt', 'cdi-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Securing a web application

Learn how to secure a web application through authentication and authorization.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to secure a web application by performing authentication and authorization using the Security feature in the Java EE 8 specification.

Authentication confirms the identity of the user by verifying a user name and password. While authorization determines whether a user has access to a specific servlet.

The security feature in Java EE provides capability to configure the basic, form or custom form authentication mechanism using annotations in the servlet.
It also provides a SecurityContext API for programmatic security checks for both web and enterprise beans resources.

You will learn how to implement form authentication. While basic authentication is only a pop up window for users to fill in their names and password, form authentication provides
an editable form for users to fill in and submit in order to log in to the system. Form authentication is more common and user-friendly in real life applications.

You will also learn how to assign permissions to different roles. This application specifies two roles: Administrator and User.

The application itself will allow users and admins to access servlets.
The `UserServlet` and `AdminServlet` simply display user information such as the name and role for the currently authenticated user.

Administrators have access to both servlets, the `UserServlet` and the `AdminServlet`. Whereas the user will only have access to the `UserServlet`.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


=== Try what you'll build

The  `finish` directory in the root of this guide contains the finished security application with form authentication. Feel free to give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following Maven goals to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```

Next, point your browser to:
// Use https://localhost:9091/ when ServletSecurity.TransportGuarantee.CONFIDENTIAL is enabled in 18003!!!!
`http://localhost:9090`
As you can see, the browser gets redirected from `http` to an `https` link automatically.

The basic registry is provided with the following user information credentials:

.Basic Registry
|===
|Username |Password|Role |Group

|alice
|alicepwd
|user
|Employee

|bob
|bobpwd
|admin, user
|Manager, Employee

|carl
|carlpwd
|admin, user
|TeamLead, Employee
|===

You can check user profiles by clicking the first or second link and signing in with one of the credentials from the Basic Registry.
You can go back to the main page to log out and switch accounts.

Notice that only admin user, Bob, = can access the second link to the `AdminServlet`.
When you sign in as Alice, you will be blocked and a message will display `Error 403: AuthorizationFailed`.

Once you are done checking out the application, stop the Open Liberty server:
```
mvn liberty:stop-server
```



// =================================================================================================
//
// =================================================================================================
== Configuring a user registry

Navigate to the  `start` directory to begin. You will not modify any code in the `backendServices` directory in this guide.

You need to set up the user registry to define users and group information. User registries store user account information, such as user name and password, that can be accessed during authentication.

To do this, add the following configurations into the `src/main/liberty/config/server.xml` file:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=security]
----

On the Open Liberty server, you can use a basic user registry to defining the users and groups information.
In real life, you will probably connect to a database that stores the user account information.

When you set up the basic user registry for authentication, the names for the users and groups must be unique.

In this application, there are three groups: `Employee`, `TeamLead` and `Manager`. Groups can be assigned to different access roles.
Within the `<application-bnd>` tags, two different authorization roles are assigned to these groups: `admin` and `user`.

A role can be mapped to a user, a group, or a special subject. The two types of special subject are `EVERYONE` and `ALL_AUTHENTICATED_USERS`.
When a role is mapped to the `EVERYONE` special subject, there is no security because everyone is allowed access and you are not prompted to enter credentials.
When a role is mapped to the `ALL_AUTHENTICATED_USERS` special subject, then any user who is authenticated by the application server can access the protected resource.

=== Encrypting passwords using securityUtility

You need to encrypt the passwords so that they will not appear as plain text in the `server.xml` file, or, in the database in real life.
It mainly protects user credentials from internal attacks, such as information leaking from the inside of an organization.

The passwords assigned to the accounts in the basic registry is encoded with Liberty's `securityUtility` command. The `securityUtility` is a command that supports plain text encryption and SSL certificate creation for Liberty.

Navigate to `liberty/wlp/bin` in the Liberty server source code you downloaded, and run the following if you have a macOS/Linux machine:
```
./securityUtility encode --encoding=xor alicepwd

./securityUtility encode --encoding=xor carlpwd
```
If you have a Windows machine, the forward slash needs to be replaced by a backward slash, such as:
```
.\securityUtility encode --encoding=xor alicepwd
```

Here, `alice` and `carl` use the XOR encoding for their passwords. While `bob` uses Advanced Encryption Standard (AES) encryption.
You need to specify a key string to be used when you encode using AES encryption. This string is hashed to produce an encryption key that is used to encrypt and decrypt the password.
The key string is provided from the `bootstrapProperties` in the `pom.xml` file.

```
./securityUtility encode --encoding=aes --key=mykey bobpwd
```

The encryption key can be provided to the server by defining the variable `wlp.password.encryption.key` and setting the value to the key. 
Setting this variable, overrides the default key that is generated. This property is set in a configuration file that should only contain this single property declaration. 
The configuration file itself is saved outside of the configuration directory for the server, this ensures that the file containing your key is not included when running the the server dump or package command.
In this application, the configuration file is saved under `src/main/liberty/config` as `pwdEncryptionKey.xml`.

// =================================================================================================
//
// =================================================================================================

== Implementing authentication

Form Authentication is an authentication mechanism where the user is able to fill in their login credentials using a form that the developers create.
Java EE provides a more convenient way to authenticate a user by calling the built-in `j_security_check` action from the login form.
The `login.html` and `error.html` pages are provided for you under the `src/main/webapp` directory. These are two frontend files that provide the login form and error page.

In order to enable form authentication, create the `UserServlet` class in the `src/main/java/io/openliberty/guides/ui/UserServlet.java` file.
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/ui/UserServlet.java[tags=security;!copyright]
----

Notice the `@FormAuthenticationMechanismDefinition` annotation in the class. The same thing can be expressed as configurations in the `web.xml`:
```
<login-config>
   <auth-method>FORM</auth-method>
   <form-login-config>
       <form-login-page>/login.html</form-login-page>
       <form-error-page>/error.html</form-error-page>
    </form-login-config>
</login-config>
```
The `@LoginToContinue` annotation allows the application to add specific login functionality to the `AuthenticationMechanism`.
The annotation links the two pages that are required for the form authentication mechanism. The pages are the `errorPage` and the `loginPage`.

At this point, your application is secured using form authentication. Users will not see the content of the servlet until they provide the correct credentials.


// =================================================================================================
//
// =================================================================================================

== Adding authorization

Authorization determines whether a user has the role required to access the `AdminServlet`.

Authorization can be achieved with the `@ServletSecurity` annotation.
Open the `src/main/java/io/openliberty/guides/ui/UserServlet.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/ui/UserServlet.java[tags=security;!copyright]
----

Note the `@HttpConstraint` annotation, it defines all the security constraints for each servlet resource.
The `admin` and `user` are roles you defined in the `server.xml` configuration file. They are declared under `rolesAllowed` so that the profile can be accessed by authenticated accounts with these two roles.
The transport guarantee defines the data protection requirements that must be satisfied by the transport. In this case, the transport guarantee is set to the CONFIDENTIAL configuration which specifies that all user data must be encrypted during transport. This ensures that the browser gets redirected from `http` to an `https` link automatically.
The Security specification also defines a common SecurityContext API that can be used to perform some common programmatic security related operations.
You can get access to the information of the authenticated account by calling the appropriate methods from the `SecurityContext` API.

The method `securityContext.isCallerInRole("admin")` returns a boolean that indicates if the current authenticated account is an `admin` or not.
The method `securityContext.getCallerPrincipal().getName()` returns the user name of the current authenticated account.

Create the `AdminServlet` class in the `src/main/java/io/openliberty/guides/ui/AdminServlet.java` file.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/ui/AdminServlet.java[tags=security;!copyright]
----

The `AdminServlet` is a servlet that displays the `inventory` service data when accessed. The same `@ServletSecurity` annotation is applied, except only `admin` roles are allowed.

The `rolesAllowed` annotation specifies that if a non-admin user such as alice signed in, she will not be able to access the `AdminServlet`.


// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

// Use https://localhost:9091/ when ServletSecurity.TransportGuarantee.CONFIDENTIAL is enabled in 18003!!!!
Use the `http://localhost:9090/` endpoint to choose the information you want to see.

Use one of the following credentials to log in:

.Basic Registry
|===
|Username |Password|Role |Group

|alice
|alicepwd
|user
|Employee

|bob
|bobpwd
|admin, user
|Manager, Employee

|carl
|carlpwd
|admin, user
|TeamLead, Employee
|===


If you choose to see the profile, once authenticated, you can see your name and role.

If you choose to see application information, once you log in, `admin` can see some basic information retrieved from the backend services.
Remember that if you log in as a user without the `admin` role, you are blocked because you do not have permission.


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Now you can write the `SecurityTest` class to test that you can access different servlets with form authentication and authorization.

Create a test class in the `src/test/java/it/io/openliberty/guides/security/SecurityTest.java` file like the following:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/security/SecurityTest.java[tags=test]
----

There are four test cases. The `testAuthenticationFail()` case tests a invalid user authentication,
while the `testAuthenticationSucceed()` case tests a successful authentication process.

The `testAuthorizationForAdmin()` and `testAuthorizationForUser()` cases verify
that only administrator account such as bob can access the application servlet to
view the backend data. However, a normal user like alice can only see an `Error 403: AuthorizationFailed`
error message.

The `executeRequestFormAuth()` method contains the main logic of testing form authentication.

First, it calls `helper.getFormLoginPage()` to send the servlet query to get the form login page.

Then, `helper.executeFormLogin()` gets invoked to execute form login and get the redirect location.

After that, `helper.accessPage()` method is called to redirect the application to the assigned page, ensure it is the original servlet request and return the right response.

In the end, the `executeRequestFormAuth()` method processes the response from an http invocation, such as validating the status code and extracting the response entity.

The detailed implementation of the helper functions are provided for you in the `src/test/java/it/io/openliberty/guides/security/util/TestUtils.java` file.


include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.security.SecurityTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.78 sec - in it.io.openliberty.guides.security.SecurityTest

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

----

To see whether the tests detect a failure, you can change some input arguments in any of the test cases.
Rerun the Maven build. You see that a test failure occurs.


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to use Java EE Security feature to authenticate and authorize users to secure your web application.

Next, you can try the related MicroProfile-JWT guide. It demonstrates technologies to secure backend services and expand on what you built here.


include::{common-includes}/finish.adoc[]
