// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: security-intro
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2018-08-11
:page-description: Learn how to secure a web application through authentication and authorization.
:page-tags: ['REST', 'MicroProfile', 'Security', 'CDI']
:page-related-guides: ['microprofile-jwt', 'cdi-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Securing a web application

Learn how to secure a web application through authentication and authorization.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to secure a web application by performing authentication and authorization using Java EE Security. Authentication confirms the identity of the user by verifying a user name and password. While authorization determines whether a user has access to restricted resources.

Java EE Security provides capability to configure the basic, form or custom form authentication mechanism using annotations in the servlets.
It also provides a SecurityContext API for programmatic security checks in Java EE containers. You will learn how to implement form authentication which allows you to specify the web application login and error pages, how to assign the security constraint of a servlet and 
how to use the SecurityContext API to determine the role of a logged in user.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


=== Try what you'll build

The  `finish` directory in the root of this guide contains the finished security application with form authentication. Feel free to give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following Maven goals to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```

Upon hitting the initial link `http://localhost:9080`, the application automatically switches from `HTTP` to `HTTPS` connection, and forwards to a login page. If the browser gives you a certificate warning, it is because the Liberty server created a SSL certificate by default. You may follow your browser's provided instructions to accept the certificate and continue.

The identity store is provided with the following user information credentials:

[#identitystoretable]
.Identity Store
|===
|Username|Password|Role|Group

|alice
|alicepwd
|user
|Employee

|bob
|bobpwd
|admin, user
|Manager, Employee

|carl
|carlpwd
|admin, user
|TeamLead, Employee

|dave
|davepwd
|
|PartTime
|===

Now you can sign in to the `HomeServlet` with one of the credentials from the identity store.

Notice that when you sign in as Bob or Carl, the browser redirects to the `admin` page and you can view their names and roles.
When you sign in as Alice, you can only view Alice's name.
When you sign in as Dave, you will be blocked and a message will display `Error 403: AuthorizationFailed` because Dave does not have a role.

Once you are done checking out the application, stop the Open Liberty server:
```
mvn liberty:stop-server
```

// =================================================================================================
//
// =================================================================================================
== Configuring the identity store

Navigate to the  `start` directory to begin.

You need to set up the identity store to define users and role information. Identity stores store user account information, such as user name and password, that can be accessed during authentication.
Typically, applications would use an external and configurable registry, like a database or Lightweight Directory Access Protocol (LDAP). However, for the purpose of this guide, a basic registry provided by Liberty is used as a simple example of an identity store.

Create the `src/main/liberty/config/server.xml` file:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=security]
----

On the Open Liberty server, you can use the basic registry as an identity store to define the users and groups information.

In this application, there are four groups: `Employee`, `TeamLead`, `Manager` and `PartTime`. Groups can be assigned to different access roles.
Within the `<application-bnd>` tags, two different authorization roles are assigned to these groups: `admin` and `user`.

A role can be mapped to a user, a group, or a special subject. The two types of special subject are `EVERYONE` and `ALL_AUTHENTICATED_USERS`.
When a role is mapped to the `EVERYONE` special subject, there is no security because everyone is allowed access and you are not prompted to enter credentials.
When a role is mapped to the `ALL_AUTHENTICATED_USERS` special subject, then any user who is authenticated by the application server can access the protected resource.

=== Encrypting passwords using securityUtility

Use the Liberty `securityUtility` command to encrypt the passwords so that they will not appear as plain text in the `server.xml` file. Navigate to the `target/liberty/wlp/bin` directory and run the following to generate an example XOR encoding for Bob:
```
./securityUtility encode --encoding=xor bobpwd

```

As you can see in the `server.xml`, all users use the XOR encoding.
// =================================================================================================
//
// =================================================================================================

== Adding authentication and authorization

Form Authentication is an authentication mechanism where the user is able to fill in their login credentials using a form that the developers create.
Java EE provides a more convenient way to authenticate a user by calling the built-in `j_security_check` action from the login form. 
The `welcome.html` and `error.html` pages are provided for you under the `src/main/webapp` directory. These are two frontend files that provide the login form and error page.

Create the `HomeServlet` class in the `src/main/java/io/openliberty/guides/ui/HomeServlet.java` file.
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/ui/HomeServlet.java[tags=homeservlet;!copyright]
----

In order to enable form authentication to the `HomeServlet`, define the `@FormAuthenticationMechanismDefinition` annotation and set its loginToContinue attribute to accept a configured `@LoginToContinue` annotation which makes `welcome.html` as the login page and `error.html` as the error page.

Authorization determines whether a user has the role required to access. It can be achieved with the `@ServletSecurity` annotation. Note that the `@HttpConstraint` annotation defines the security constraints.
The `admin` and `user` are roles you defined in the `server.xml` configuration file. They are declared under 
`rolesAllowed` attribute so that the `HomeServlet` can be accessed by authenticated accounts with these two roles.

The `transportGuarantee` defines the data protection requirements that must be satisfied by the transport. In this case, it is set to the `CONFIDENTIAL` configuration which specifies that all user data must be encrypted during transport. This ensures that the browser gets redirected from `http` to an `https` link automatically.

The Security specification also defines a common SecurityContext API that can be used to perform some common programmatic security related operations. You can get access to the information of the authenticated account by calling the appropriate methods from the SecurityContext API.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/ui/HomeServlet.java[tags=doget]
----

The `doGet()` method uses the `securityContext.isCallerInRole()` API to determine the current user's role  and forward the repsonse to a proper page.

Open the `src/main/webapp/WEB-INF/web.xml` file:
[source, xml]
----
include::finish/src/main/webapp/WEB-INF/web.xml[tags=security]
----

Note that the `security-constraint` is used to restrict the access of different resources. The `user.jsf` and `admin.jsf` pages can only be accessed by whoever has user or admin roles respectively.
// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Point your browser to `http://localhost:9080`. As you can see, the browser gets redirected from `http` to an `https` link automatically while `index.html` switches to the `HomeServlet`, this is accomplished through the transport guarantee defined in the `HomeServlet`. 
Because the `HomeServlet` also specifies the loginPage and errorPage attributes of the @LoginToContinue annotation in @FormAuthenticationMechanismDefinition, the login `welcome.html` is prompted for authentication.

Use one of the credentials from the above table `Identity Store` to log in.

// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Now you can write the `SecurityTest` class to test the authentication and authorization of the application.

Create the `SecurityTest` class in the `src/test/java/it/io/openliberty/guides/security/SecurityTest.java` file like the following:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/security/SecurityTest.java[tags=test]
----

The `testAuthenticationFail()` method tests an invalid user authentication,
while the `testAuthorizationFail()` method tests a user that exists in the identity store but is not authorized to access the application.

The `testAuthorizationForAdmin()` and `testAuthorizationForUser()` methods verify
that an administrator account such as bob should be routed to the `admin` page. However, a normal user like alice should be routed to the `user` page.

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.security.SecurityTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.78 sec - in it.io.openliberty.guides.security.SecurityTest

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

----

To see whether the tests detect a failure, you can change some input arguments in any of the test methods.
Rerun the Maven build. You see that a test failure occurs.


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to use Java EE Security feature to authenticate and authorize users to secure your web application.

Next, you can try the related https://openliberty.io/guides/microprofile-jwt.html[MicroProfile-JWT] guide. It demonstrates technologies to secure backend services.


include::{common-includes}/finish.adoc[]

