// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: security-intro
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2018-08-11
:page-description: Learn how to secure a web application through authentication and authorization.
:page-tags: ['REST', 'MicroProfile', 'Security', 'CDI']
:page-related-guides: ['microprofile-jwt', 'cdi-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Securing a web application

Learn how to secure a web application through authentication and authorization.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to secure a web application by performing authentication and authorization using Security feature in the Java EE 8 specification.

The security feature in Java EE provides capability to configure the basic, form or custom form authentication mechanism using annotations in the servlet.
It also provides a SecurityContext API for programmatic security checks for both web and enterprise beans resources.

The application that you will be working with is an `inventory` service, which stores the information about various JVMs that run on different systems.
Whenever a request is made to the inventory service to retrieve the JVM system properties of a particular host, the inventory service communicates with the `system` service on that host to get these system properties.
The code for the backend services are provided for you, and you will wrap these services by a security layer that performs proper authentication and authorization.

You will learn how to implement form authentication. Authentication confirms the identity of the user by verifying a user name and password.
You will also learn how to assign permissions to different roles. Authorization determines whether a user has access to a specific role within the system. This application specifies two roles: Administrator and User.

The application itself will allow users and admins to access servlets. Administrators have access to both servlets, the `ProfileServlet` and the `ApplicationServlet`. Whereas the user will only have access to the `ProfileServlet`.


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


=== Try what you'll build

The  `finish` directory in the root of this guide contains the finished security application with form authentication. Feel free to give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following Maven goals to build the application and run it inside Open Liberty:

`mvn install liberty:start-server`

Next, point your browser to:

`http://localhost:9090`

The basic registry is provided with the following user information credentials:

.Basic Registry
|===
|Username |Password|Role |Group

|alice
|alicepwd
|user
|Employee

|bob
|bobpwd
|admin, user
|Manager, Employee

|carl
|carlpwd
|admin, user
|TeamLead, Employee
|===

You can check user profiles by clicking the first link and signing in with one of the credentials from the Basic Registry.
You can go back to the main page to log out and switch accounts.

You can access to the `inventory` service data by clicking the second link and signing in as either bob or carl.
When you sign in as alice, you will be blocked and a message will display `Error 403: AuthorizationFailed`.

Once you are done checking out the application, stop the Open Liberty server:
`mvn liberty:stop-server`



// =================================================================================================
//
// =================================================================================================
== Configuring a user registry

Navigate to the  `start/frontendUI` directory to begin. You will not modify any code in the `backendServices` directory in this guide.

You need to set up the user registry to define users and group information. To do this, add the following configurations into the `src/main/liberty/config/server.xml` file:

[source, xml, indent=0]
----
include::finish/frontendUI/src/main/liberty/config/server.xml[tags=security]
----

When you set up the basic user registry for authentication, the names for the users and groups must be unique.

In this application, there are three groups: `Employee`, `TeamLead` and `Manager`.
Within the `<application-bnd>` tags, two different authorization roles are assigned to these groups: `admin` and `user`.

A role can be mapped to a user, a group, or a special subject. The two types of special subject are `EVERYONE` and `ALL_AUTHENTICATED_USERS`.
When a role is mapped to the `EVERYONE` special subject, there is no security because everyone is allowed access and you are not prompted to enter credentials.
When a role is mapped to the `ALL_AUTHENTICATED_USERS` special subject, then any user who is authenticated by the application server can access the protected resource.

=== Encrypting passwords using securityUtility

The passwords assigned to the accounts in the basic registry is encoded with Liberty's `securityUtility` command. The `securityUtility` is a command that supports plain text encryption and SSL certificate creation for Liberty.

Navigate to `liberty/wlp/bin` in the Liberty server source code you downloaded, and run:
```
./securityUtility encode --encoding=xor alicepwd

./securityUtility encode --encoding=xor carlpwd
```
Here, `alice` and `carl` use the xor encoding for their passwords. While `bob` uses aes encryption with an encrypting key from `bootstrapProperties` predefined in the `pom.xml` file.
```
./securityUtility encode --encoding=aes --key=mykey bobpwd
```

// =================================================================================================
//
// =================================================================================================

== Implementing authentication

Form Authentication is an authentication mechanism where the user is able to fill in their login credentials using a form that the developers create.
Java EE provides a more convenient way to authenticate a user by calling the built-in `j_security_check` action from the login form.
The `login.html` and `error.html` pages are provided for you under the `src/main/webapp` directory.

In order to enable form authentication, create the `ProfileServlet` class in the `src/main/java/io/openliberty/guides/ui/ProfileServlet.java` file.
[source, java, indent=0]
----
include::finish/frontendUI/src/main/java/io/openliberty/guides/ui/ProfileServlet.java[tags=security;!copyright]
----

Notice the `@FormAuthenticationMechanismDefinition` annotation in the class. The same thing can be expressed as configurations in the `web.xml`:
```
<login-config>
   <auth-method>FORM</auth-method>
   <form-login-config>
       <form-login-page>/login.html</form-login-page>
       <form-error-page>/error.html</form-error-page>
    </form-login-config>
</login-config>
```
The `@LoginToContinue` annotation allows the application to add specific login functionality to the `AuthenticationMechanism`.
The annotation links the two pages that are required for the form authentication mechanism. The pages are the `errorPage` and the `loginPage`.

At this point, your application is secured using form authentication. Users will not see the content of the servlet until they provide the correct credentials.


// =================================================================================================
//
// =================================================================================================

== Implementing authorization

Authorization determines whether a user has the role required to access certain resources within the system.

Authorization can be achieved with the `@ServletSecurity` annotation.
Open the `src/main/java/io/openliberty/guides/ui/ProfileServlet.java` file:

[source, java, indent=0]
----
include::finish/frontendUI/src/main/java/io/openliberty/guides/ui/ProfileServlet.java[tags=security;!copyright]
----

Note the `@HttpConstraint` annotation, it defines all the security constraints for each servlet resource.
The `admin` and `user` are roles you defined in the `server.xml` configuration file. They are declared under `rolesAllowed` so that the profile can be accessed by authenticated accounts with these two roles.
The `transportGuarantee=ServletSecurity.TransportGuarantee.CONFIDENTIAL` configuration indicates that all user data must be encrypted by the transport.

The Security specification also defines a common SecurityContext API that can be used to perform some common programmatic security related operations.
You can get access to the container provided `SecurityContext` by using CDI injection and call the appropriate methods.

The method `securityContext.isCallerInRole("admin")` returns a boolean that indicates if the current authenticated account is an `admin` or not.
The method `securityContext.getCallerPrincipal().getName()` returns the user name of the current authenticated account.

Create the `ApplicationServlet` class in the `src/main/java/io/openliberty/guides/ui/ApplicationServlet.java` file.

[source, java, indent=0]
----
include::finish/frontendUI/src/main/java/io/openliberty/guides/ui/ApplicationServlet.java[tags=security;!copyright]
----

The `ApplicationServlet` is a servlet that displays the `inventory` service data when accessed. The same `@ServletSecurity` annotation is applied, except only `admin` roles are allowed.

The `rolesAllowed` annotation specifies that if a non-admin user such as alice signed in, she will not be able to access the `ApplicationServlet`.


// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Use the `http://localhost:9090/` endpoint to choose the information you want to see.

Use one of the following credentials to log in:

.Basic Registry
|===
|Username |Password|Role |Group

|alice
|alicepwd
|user
|Employee

|bob
|bobpwd
|admin, user
|Manager, Employee

|carl
|carlpwd
|admin, user
|TeamLead, Employee
|===


If you choose to see the profile, once authenticated, you can see your name and role.

If you choose to see application information, once you log in, `admin` can see some basic information retrieved from the backend services.
Remember that if you log in as a user without the `admin` role, you are blocked because you do not have permission.
include::{common-includes}/mvncompile.adoc[]

// =================================================================================================
// Testing the application
// =================================================================================================


// =================================================================================================
// Great work! You're done!
// =================================================================================================

== Great work! You're done!

You learned how to use Java EE Security feature to authenticate and authorize users to secure your web application.

Next, you can try the related MicroProfile-JWT guide. It demonstrates technologies to secure backend services and expand on what you built here.


include::{common-includes}/finish.adoc[]
