// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-security
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2017-12-11
:page-description: Learn how to use the
:page-tags: ['REST', 'MicroProfile', 'Security', 'CDI']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Securing a web application. OR Building a secure web application.

Learn how to use appSecurity-3.0 to secure a web application.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to secure your web application by performing authentication and authorization. 

Authentication confirms the identity of the user. The most common authentication is user name and password, through basic authentication or form authentication. In this application we will be showing both methods of authentication. You will be setting up a basic user registry with test variables. 

--
--
--

Authorization determines whether a user has access to a specific role within the system. In this application we will have two roles: Administrator and User. 

--
--
--

The application itself shows certain users properties of their system. Administrators have access to see the all the system properties whereas users will not have access to see any of the system properties.

[I think I can refine this so that the users will see partial information]


// =================================================================================================
== Getting Started
// =================================================================================================


The fastest way to work through this guide is to clone the Git repository and use the projects that are provided inside:

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-{projectid}.git
cd guide-{projectid}
----

The `start` directory contains the starting project that you will build upon.

The `finish` directory contains the finished project, which is what you will build.

*Try what you'll build*

The  `finish` directory in the root of this guide contains the finished events application. Feel free to give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following Maven goals to build the application and run it inside Open Liberty:

`mvn install liberty:start-server`

After starting the application, you can access the following " " to test the application:

`http://localhost:9080/LibertyProject`

~SCENARIO~

As mentioned above, you can access this application under two different roles:

.Basic Registry
|===
|Username |Password|Role

|bob
|pwd
|myAdmins

|alice
|alicepwd
|myUsers
|===


Try out the authentication of the application by signing in with either credentials from the Basic Registry. 

* Try out the authorization of the application, sign in as Bob, view the system properties.

* When you sign in as Alice, you will not have access.


Once you are done checking out the application, stop the Open Liberty server:
`mvn liberty:stop-server`



// =================================================================================================
//
// =================================================================================================
== Configuration
* Configure the basic registry and roles
* Add the following into the server.xml file 

```a
<basicRegistry id="basic" realm="WebRealm">
    <user name="bob" password="{xor}Lyg7" />  <!-- pwd -->
    <user name="alice" password="{xor}PjM2PDovKDs=" />  <!-- alicepwd -->
    <user name="carl" password="{xor}PD4tMy8oOw==" />   <!-- carlpwd -->

    <group name="myAdmins">
      <member name="bob" />
    </group>

    <group name="myUsers">
      <member name="bob" />
      <member name="alice" />
      <member name="carl" />
    </group>
  </basicRegistry>
```
* You can define users and groups in the basic user registry for authentication. 
* The names for users and groups must be unique. 
* In our case, we have a group called "myAdmins" and another group called "myUsers".

== Authentication
* FormAuthenticationMechanismDefinition annotation

* Insert the following annotation in the LoginBean.java file

```
@FormAuthenticationMechanismDefinition(
  loginToContinue = @LoginToContinue(
    loginPage = "/login.jsf",
    errorPage = "/loginerror.jsf",
    useForwardToLogin = true)
  )

```

== Authorization 
*Authorization with specific roles can be achieved using the following annotations 

** @DeclareRoles()
** @RolesAllowed()

* These annotations allow you to specify the roles of each user group without configuration in the server.xml file. The group to role mapping is accomplished automatically as long as the user group names and the role names are identical. 

* Add the following annotations to the PropertiesResource.java file:

```
// tag::class[]
@Path("properties")
@DeclareRoles({"myAdmins", "myUsers"})
public class PropertiesResource {
// end::class[]

    // tag::getProperties[]
    @GET
    @RolesAllowed("myAdmins")
    @Produces(MediaType.APPLICATION_JSON)
    public JsonObject getProperties() {

        JsonObjectBuilder builder = Json.createObjectBuilder();

        System.getProperties()
              .entrySet()
              .stream()
              .forEach(entry -> builder.add((String)entry.getKey(),
                                            (String)entry.getValue()));

       return builder.build();
    }
    // end::getProperties[]
}
```

* Notice how the roles "myAdmins" and "myUsers" are identical to the group names we set up earlier in the basic registry. They must be exactly the same for the mapping to work.

* The properties are only allowed by users of the role "myAdmins".

// =================================================================================================
// Building the application
// =================================================================================================

== Building the application
include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To see the new application in action, run the Maven `liberty:start-server` command from the `start` directory:

[source]
----
$ mvn liberty:start-server
----




// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

* Testing Authentication
  - request.login() with correct credentials 
  - request.login() with incorrect credentials and checking for the correct exception

* Testing Authorization
  - checking if eventAdmin has access to list of people registered for events
  - checking that registeredUser does not have access to list of people registered for events


=== Running the tests



== Great work! You're done!

include::{common-includes}/finish.adoc[]
