// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-security
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2017-12-11
:page-description: Learn how to use the
:page-tags: ['REST', 'MicroProfile', 'Security', 'CDI']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Securing a web application

Learn how to secure a web application through form authentication and authorization.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to secure a web application by performing authentication and authorization.

Authentication confirms the identity of the user. The most common type of authentication is through basic authentication or form authentication using user name and password.
Both basic authentication and form authentication do not protect login credentials through the HTTP response.

This application demonstrates form authentication, which is slightly more secured. A log out functionality will be implemented and there is also an automatic log out after a certain amount of time of inactivity.
Authorization determines whether a user has access to a specific role within the system. This application specifies two roles: Administrator and User.

The application itself allows users and admins to access servlets. Administrators have access to both servlets, the `HelloServlet` and the `AdminServlet`. Whereas the user will only have access to the `HelloServlet`.


// =================================================================================================
== Getting Started
// =================================================================================================


The fastest way to work through this guide is to clone the Git repository and use the projects that are provided inside:

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-{projectid}.git
cd guide-{projectid}
----

The `start` directory contains the starting project that you will build upon.

The `finish` directory contains the finished project, which is what you will build.

*Try what you'll build*

The  `finish` directory in the root of this guide contains the finished security application with form authentication. Feel free to give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following Maven goals to build the application and run it inside Open Liberty:

`mvn install liberty:start-server`

Next, point your browser to:

`https://localhost:9080`

The application can be accessed under two different roles:

.Basic Registry
|===
|Username |Password|Role

|bob
|bobpwd
|admin

|alice
|alicepwd
|user
|===

You can try out the authentication of the application by clicking the first link and signing in with either credentials from the Basic Registry. You can try the authorization by clicking the second link and signing in as Bob to view the AdminServlet. When you sign in as Alice, you will not have access to the AdminServlet.

In order to sign in as different users, you must close the browser and re-open it at the same link.

Once you are done checking out the application, stop the Open Liberty server:
`mvn liberty:stop-server`



// =================================================================================================
//
// =================================================================================================
== Configuring a user registry

Navigate to the  `start` directory to begin.

The user registry is set up to define users and group information. To do this, you need to add the following `Basic Registry` into the `src/main/liberty/configserver.xml` file:

[source, xml, indent=0]
----
include::finish/src/main/liberty/config/server.xml[tags=security]
----

Now that you have defined users and groups in the basic user registry for authentication. The names for the users and groups must be unique. In this application, there is a group called "admin" and another group called "user".

The password is encoded with Liberty's `securityUtility` command. The securityUtility is a command that supports plain text encryption and SSL certificate creation for Liberty. Here, the application uses the xor encoding. There are two other supported encodings are well: hash and aes that can be used.


// =================================================================================================
//
// =================================================================================================

== Implementing authentication

Authentication is implemented in order to confirm the identity of the user. This application currently uses Basic Authentication, which is a simple method to authenticate a user with a username and password.
The request is sent with an Authorization header that contains the word `Basic` followed by a base64-encoded string in the format `username:password`.

Open the `AdminServlet` class in the `src/main/java/io/openliberty/guides/hello/AdminServlet.java` file.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/example/AdminServlet.java[tags=security;!copyright]
----

Notice the `@BasicAuthenticationMechanismDefinition` annotation in the class. The realm name is specified in the annotation as `webRealm`, this maps to the same realm name defined in the Basic User Registry
.
At this point, your application is secured using basic authentication. You can try running this now using the instructions from `Try What You'll Build` in the `start` directory.

The next type of authentication that will be implemented is Form Authentication. Form Authentication is an authentication mechanism where the user is able to fill in their login credentials using a form that the developer is able to edit.

It is more secure than Basic Authentication because logout functionality can be implemented and the user will be logged out automatically after a certain amount of time.

To configure Form Authentication, remove the `@BasicAuthenticationMechanismDefinition` and replace it with `@FormAuthenticationMechanismDefinition`.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/hello/HelloServlet.java[tags=security;!copyright]
----

The `LoginToContinue` annotation allows the application to add specific login functionality to the `AuthenticationMechanism`. The elements in this annotation are the `errorPage` and the `loginPage`. These are resources that the caller will see depending on if they provide the correct credentials.


// =================================================================================================
//
// =================================================================================================

== Implementing authorization

Authorization determines whether a user has access to a certain role within the system.

Authorization can be achieved with the annotation `@ServletSecurity`. Create the `HelloServlet` class in the `src/main/java/io/openliberty/guides/hello/HelloServlet.java` file:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/hello/HelloServlet.java[tags=security;!copyright]
----

The roles "admin" and "user" are identical to the group names in the basic registry. They must be exactly the same for the mapping to work. They are declared under rolesAllowed so that the Hello Servlet can only be accessed by those two user groups.

Create the `AdminServlet` class in the `src/main/java/io/openliberty/guides/hello/AdminServlet.java` file. The same `@ServletSecurity` annotation is applied, except only "admin" roles are allowed. `AdminServlet` is a servlet that displays the message `Hello Admin! How are you today?` when accessed.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/hello/AdminServlet.java[tags=security;!copyright]
----

The `@ServletSecurity` annotation specifies that even if a "user" such as Alice is signed in, they will not be able to access the Admin Servlet.


// =================================================================================================
// Building the application
// =================================================================================================

== Building the application
include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Create the test class, `src/test/java/io/openliberty/guides/hello/it/SecurityTest.java`.


[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/servlet/SecurityTest.java[tags=security;!copyright]
----


=== Running the tests



== Great work! You're done!

include::{common-includes}/finish.adoc[]
